polls/urls.py
from django.conf.urls import patterns,url,include

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>[0-9]+)/$', views.post, name='detail'),
    url(r'^(?P<post_id>[0-9]+)/addcomment/$', views.addComment, name = 'addcomment'),
    url(r'^auth/',include('userssys.urls'))
]

prog/urls.py
from  django.conf.urls import include, url
from  django.conf import settings
from  django.conf.urls.static import static
from  django.contrib import admin



from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),
    url(r'^',include('polls.urls'))
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userssys/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^register/$', views.register),

]

polls/models.py
import datetime
from django.db import models
from django.forms import ModelForm
from django.utils import timezone

class Post(models.Model):
    post_header = models.CharField(default = '',max_length = 100)
    posts_auftor_name = models.CharField(default = '',max_length=100)
    post_text = models.TextField(max_length = 200)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
    	return self.post_header

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Image(models.Model):
     images_post = models.ForeignKey(Post)
     image = models.ImageField(upload_to ='images/',
                               height_field = "height_field",
                               width_field = "width_field")
     height_field = models.IntegerField(default = 0)
     width_field = models.IntegerField(default = 0)

class File(models.Model):
    files_pots = models.ForeignKey(Post)
    file = models.FileField(upload_to = '/files/')


class Comment(models.Model):
    comments_post = models.ForeignKey(Post)
    comment_text = models.TextField(verbose_name='Текст коментаря')
    comments_auftor_name = models.CharField(default = '',max_length=100)
    comment_pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment_text

# Create your models here.

userssys/models.py
from django.db import models

# Create your models here.

polls/forms.py
from django import forms
from  django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.context_processors import csrf
from  django.contrib import auth
from django.utils.translation import ugettext as _


from .models import Post,Comment,Image
from .forms import CommentForm



def index(request):
    post_list = Post.objects.order_by('-pub_date')
    auth_name = auth.get_user(request).username
    context = {'authName':auth_name, 'post_list': post_list,'username':auth.get_user(request).username}
    context.update(csrf(request))
    if request.POST:
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return HttpResponseRedirect('/polls/')
        else:
            context['login_error'] = "Акаунт не знайденно"
            return render(request,'userssys/login.html',context)
    else:
        return render(request, 'polls/index.html', context)


def addComment(request,post_id):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.comments_post = Post.objects.get(id= post_id)
            comment.comments_auftor_name = auth.get_user(request).username
            form.save()
        return  HttpResponseRedirect('/polls/%s/' %post_id)

def post(request,post_id=1):

    coment_form = CommentForm
    coment_form.comments_post_id = post_id
    args = {}
    args.update(csrf(request))
    args['post'] = Post.objects.get(id = post_id)
    args['username']  = auth.get_user(request).username
    args['images'] = Image.objects.filter(images_post_id = post_id)
    args['comments'] = Comment.objects.filter(comments_post_id = post_id)
    args['form'] = coment_form
    return  render(request,'polls/detail.html',args)

userssys/views.py
from django.shortcuts import get_object_or_404, render,render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.context_processors import csrf
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm



def login(request):
    args ={}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return HttpResponseRedirect('/polls/')
        else:
            args['login_error'] = "Аккаунт не знайдено"
            return render(request,'userssys/login.html',args)
    else:
        return render(request,'userssys/login.html',args)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/polls/')

def register(request):
    args ={}
    args.update(csrf(request))
    args['form'] = UserCreationForm
    if request.POST:
        newuser_form = UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'],password=newuser_form.cleaned_data['password1'])
            auth.login(request,newuser)
            return HttpResponseRedirect('/polls/')
        else:
            args['form'] = newuser_form
    return render(request,'userssys/register.html',args)

polls/templates/polls/detail.html
{%extends 'main.html'%}
{% load i18n %}

{%block postsAuthorName%}

    <h3>{% trans "Автор статті" %}</h3>
    <p class="postAuft"> {{post.posts_auftor_name}}</p>

{% endblock %}

{%block posts%}



        <div class="mainContent">
            <div class="content">
                        <article class="typicalArticle">
                            <header>
                                <h3><a href="{% url 'polls:detail' post.id %}">{{ post.post_header }}</a></h3>
                            </header>

                            <footer>
                                <p class="postInfo">{{post.pub_date}}</p>
                            </footer>

                                <content>
                                    {% if images%}
                                    {%for image in images%}
                                    <img src="{{ image.image.url }}" class="image">

                                    {%endfor%}
                                    {%endif%}
                                    <p>{{ post.post_text }}</p>
                                </content>

                        </article>

                        <p class = "comentTitle">{% trans "Комментарі: "%}</p>

                        {% for comment in comments %}
                                <p class="auftCommentName">{{comment.comments_auftor_name}}</p>
                                <p>{{comment.comment_text}}</p>
                                <p class="postInfo">
                                    {{comment.comment_pub_date}}
                                </p>
                        {%endfor%}
                        {%if username%}
                        <comment class = 'comment'>
                            <form action="/polls/{{post.id}}/addcomment/" method="post">
                                {% csrf_token %}
                                <p class="string">{% trans "Текст коментаря: "%}</p>
                                 <reg class="regFields">{{ form.comment_text}}</reg>

                                <input type="submit" class="button" value="{% trans "Відправти"%}"/>
                            </form>

                        </comment>
                        {%endif%}
            </div>

        </div>
{%endblock%}

polls/templates/polls/index.html
{%extends "main.html"%}
{% load i18n %}
{%block login%}

        <h3 class="regTitle">{% trans "Авторизація"%}</h3>
        <form action = "/polls/auth/login/" method="post">
        {% csrf_token%}
            <p class = "string"><label for="username">{% trans "Ім'я користувача"%}</label></p>
            <reg class = "regFields"><input type="text" name="username" id="username"></reg>
            <p class = "string"><label for="password">{% trans "Пароль користувача"%}</label></p>
            <reg class = "regFields"><input type="password" name="password" id="password"></reg>
            {%if login_error%}
                <p class="wrongData">
                <label class="error">{{ login_error }}</label>
                </p>
            {%endif%}


            <input class="button" type="submit" value="{% trans "Увійти" %}"/>

            <p class="string"><a href="/polls/auth/register/">{% trans "Реєстрація"%}</a> </p>
        </form>

{% endblock %}

{% block privateRoom %}
    <h3 class="regTitle">{{authName}}</h3>
    <p class="string"><a href="/polls/auth/logout/">{% trans "Вийти"%}</a> </p>
{% endblock %}

{%block posts%}
        <div class="mainContent">
            <div class="content">
                     {% if post_list %}
                        {% for post in post_list %}
                        <article class="typicalArticle">
                            <header>
                                <h3><a href="{% url 'polls:detail' post.id %}">{{ post.post_header }}</a></h3>
                            </header>

                            <footer>
                                <p class="postInfo">{{post.pub_date}}</p>
                            </footer>

                                <content>
                                    <p>{{ post.post_text }}</p>
                                </content>
                        </article>
                            {% endfor %}
                    {% else %}
                        <p>No polls are available.</p>
                    {% endif %}
                </div>
        </div>
{%endblock%}

templates/main.html
<!DOCTYPE html>
    <html lang = "en">
    {% load i18n %}
    {% load staticfiles %}

    <head>
        <title></title>
        <meta charset="utf-8"/>

        <link rel="stylesheet" type="text/css" href="{% static 'userssys/style.css' %}" />
        <meta name="vieport content ="width-device-width, intital-scale =1.0">
    </head>
    <body class="body">


        <header class="mainHead">
            <nav><ul>

                <li class="active"><a href="{% url 'polls:index' %}">{% trans "Головна сторінка" %}</a></li>
                <li><a href = "#">{% trans "Новини" %}</a> </li>
                <li><a href = "#">{% trans "Завантажити" %}</a> </li>
                <li><a href = "#">{% trans "Вікі" %}</a> </li>

            </ul></nav>
        </header>

        <aside class="sideInfo">
            {% block postsAuthorName %}{{ selection.postsAuthorName }}{% endblock %}
            {% if username %}
                {% block privateRoom %}{%endblock%}
            {%else%}
                {% block login %}{%endblock%}
            {%endif%}
            {% block register %}{%endblock%}
        </aside>

        {% block posts %}{{ selection.posts }}{% endblock %}

        <footer class="mainFooter">
            <p>Copyright &copy;2015 by Andriy Eromenko</p>
        </footer>
    </body>

</html>

userssys/templates/userssys/login.html
{%extends 'main.html'%}
{% load i18n %}
{%block login%}

        <h3 class="regTitle">{% trans "Авторизація" %}</h3>
        <form action = "/polls/auth/login/" method="post">
        {% csrf_token%}
            <p class = "string"><label for="username">{% trans "Ім'я користувача" %}</label></p>
            <reg class = "regFields"><input type="text" name="username" id="username"></reg>
            <p class = "string"><label for="password">{% trans "Пароль користувача"%}</label></p>
            <reg class = "regFields"><input type="password" name="password" id="password"></reg>
            {%if login_error%}

                <p class="wrongData">{%trans "Аккаунт не знайденно"%}</p>

            {%endif%}


            <input class="button" type="submit" value="{% trans "Увійти" %}">

            <p class="string"><a href="/polls/auth/register/">{% trans "Реєстрація"%}</a> </p>
        </form>

{% endblock %}

userssys/templates/userssys/register.html
{%extends 'main.html'%}
{% load i18n %}
{%block register %}

        <h3 class="regTitle">{% trans "Реєстрація" %}</h3>
        <form action="/polls/auth/register/" method="post">
        {% csrf_token %}
        <p class="string">{% trans "Ім'я користувача" %}</p>
        <reg class="regFields">{{ form.username }}</reg>
        <p class="string">{% trans "Пароль користувача" %}</p>
            <reg class="regFields">{{form.password1}}</reg>
            <p class = "string">{% trans "Повторіть пароль" %}</p>
            <reg class = "regFields">{{form.password2}}</reg>
        <input type="submit" class = 'button' value="{% trans "Зареєструватися"%}"/>
        </form>

{%endblock%}